name: Test-Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - dev
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    steps:
        - uses: actions/checkout@v3
        - name: Use Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '16.x'
        - name: Build Frontend
          run: |
            npm install
            npm run build
             